function initializeVotePayload(payload) {
  const {
    amendment,
    bill,
    chamber,
    congress,
    date,
    description,
    documentNumber,
    documentTitle,
    id,
    nomination,
    question,
    questionText,
    rollCall,
    session,
    source,
    time,
    url,
    voteType,
  } = payload

  return {
    amendment: {
      apiUri: amendment.api_uri,
      number: amendment.number,
      sponsor: amendment.sponsor,
      sponsorId: amendment.sponsor_id,
      sponsorParty: amendment.sponsor_party,
      sponsorState: amendment.sponsor_state,
      sponsorUri: amendment.sponsor_uri,
    },
    bill: {
      apiUri: bill.api_uri,
      billId: bill.bill_id,
      latestAction: bill.latest_action,
      number: bill.number,
      title: bill.title,
      titleShort: bill.short_title,
    },
    chamber: chamber.toLowerCase(),
    congress,
    date,
    description,
    documentNumber,
    documentTitle,
    id,
    nomination,
    question,
    questionText,
    rollCall,
    session,
    source,
    time,
    url,
    voteType,
  }
}

export default initializeVotePayload
