import mapLegislatorCommittee from "./mapLegislatorCommittee"
import prepareStateName from "./prepareStateName"

function mapLegislatorRole(role) {
  const {
    at_large: atLarge,
    bills_cosponsored: billsCosponsored,
    bills_sponsored: billsSponsored,
    chamber,
    committees,
    congress,
    contact_form: contactForm,
    cook_pvi: cookPvi,
    district,
    dw_nominate: dwNominate,
    end_date: endDate,
    fax,
    fec_candidate_id: fecCandidateId,
    ideal_point: idealPoint,
    leadership_role: leadershipRole,
    lis_id: lisId,
    missed_votes: missedVotes,
    missed_votes_pct: missedVotesPercent,
    next_election: nextElection,
    ocd_id: ocdId,
    office,
    party,
    phone,
    senate_class: senateClass,
    seniority,
    start_date: startDate,
    state,
    state_rank: stateRank,
    subcommittees,
    title,
    short_title: titleShort,
    total_present: totalPresent,
    total_votes: totalVotes,
    votes_against_party_pct: votesAgainstPartyPercent,
    votes_with_party_pct: votesWithPartyPercent,
  } = role

  return {
    atLarge,
    billsCosponsored,
    billsSponsored,
    chamber,
    committees: committees.map(mapLegislatorCommittee),
    congress,
    contactForm,
    cookPvi,
    district,
    dwNominate,
    endDate,
    fax,
    fecCandidateId,
    idealPoint,
    leadershipRole,
    lisId,
    missedVotes,
    missedVotesPercent,
    nextElection,
    ocdId,
    office,
    party,
    phone,
    senateClass,
    seniority,
    startDate,
    state,
    stateName: prepareStateName(state),
    stateRank,
    subcommittees: subcommittees.map(mapLegislatorCommittee),
    title,
    titleShort,
    totalPresent,
    totalVotes,
    votesAgainstPartyPercent,
    votesWithPartyPercent,
  }
}

export default mapLegislatorRole
